// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DeviceManagementDbContext))]
    [Migration("20251213104715_AddReturnRequestToDeviceAssignment")]
    partial class AddReturnRequestToDeviceAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Entities.AiChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("FileMimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("AiChatMessages");
                });

            modelBuilder.Entity("backend.Models.Entities.AiChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AiChatSessions");
                });

            modelBuilder.Entity("backend.Models.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Departme__3214EC07A2FFC172");

                    b.HasIndex("DeletedBy");

                    b.HasIndex(new[] { "DepartmentCode" }, "UQ__Departme__6EA8896D4A9F22D8")
                        .IsUnique()
                        .HasFilter("[DepartmentCode] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("backend.Models.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("CurrentDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("PurchasePrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("WarrantyExpiry")
                        .HasColumnType("date");

                    b.Property<string>("WarrantyProvider")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Devices__3214EC0792B50178");

                    b.HasIndex("CurrentDepartmentId");

                    b.HasIndex("CurrentUserId");

                    b.HasIndex("ModelId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "DeviceCode" }, "UQ__Devices__AFFB3E95FA254E69")
                        .IsUnique()
                        .HasFilter("[DeviceCode] IS NOT NULL");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("AssignedToDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReturnRequestReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReturnRequestedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__DeviceAs__3214EC07E23AE668");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToDepartmentId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("DeviceAssignments");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ActionBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__DeviceHi__3214EC070FB087A7");

                    b.HasIndex("ActionBy");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceHistories");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__DeviceMo__3214EC07CED0F119");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("DeviceModels");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceQrToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("DeviceQrTokens");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceStatusLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__DeviceSt__3214EC0714BE7117");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceStatusLogs");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__DeviceTy__3214EC0721C80881");

                    b.HasIndex(new[] { "TypeName" }, "UQ__DeviceTy__D4E7DFA82A395CD1")
                        .IsUnique();

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("backend.Models.Entities.IncidentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("RejectedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReportDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReportType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ReportedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Severity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Incident__3214EC07ADDFD2E3");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RejectedBy");

                    b.HasIndex("ReportedByUserId");

                    b.ToTable("IncidentReports");
                });

            modelBuilder.Entity("backend.Models.Entities.Liquidation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LiquidationDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Liquidat__3214EC07D1780218");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("DeviceId");

                    b.ToTable("Liquidations");
                });

            modelBuilder.Entity("backend.Models.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC07F06D090A");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("backend.Models.Entities.Repair", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<Guid?>("AssignedToTechnicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CostApprovedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CostApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<Guid?>("IncidentReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("LaborHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("RejectedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RepairCompany")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RepairDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Repairs__3214EC077E3E8938");

                    b.HasIndex("AssignedToTechnicianId");

                    b.HasIndex("CostApprovedBy");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IncidentReportId");

                    b.HasIndex("RejectedBy");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("backend.Models.Entities.RepairFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("RepairId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__RepairFe__3214EC0761203305");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RepairId");

                    b.ToTable("RepairFeedback", (string)null);
                });

            modelBuilder.Entity("backend.Models.Entities.RepairImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsAfterRepair")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<Guid?>("RepairId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__RepairIm__3214EC079125F113");

                    b.HasIndex("RepairId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("RepairImages");
                });

            modelBuilder.Entity("backend.Models.Entities.Replacement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NewDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OldDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PerformedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReplacementDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Replacem__3214EC07731C4418");

                    b.HasIndex("NewDeviceId");

                    b.HasIndex("OldDeviceId");

                    b.HasIndex("PerformedById");

                    b.ToTable("Replacements");
                });

            modelBuilder.Entity("backend.Models.Entities.ReportExport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExportDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("ExportedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReportType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__ReportEx__3214EC077623BF99");

                    b.HasIndex("ExportedBy");

                    b.ToTable("ReportExports");
                });

            modelBuilder.Entity("backend.Models.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Supplier__3214EC07D8C72F35");

                    b.HasIndex("DeletedBy");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("backend.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07B39D4626");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534235D947A")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Entities.AiChatMessage", b =>
                {
                    b.HasOne("backend.Models.Entities.AiChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AiChatMessages_AiChatSessions");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("backend.Models.Entities.AiChatSession", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "User")
                        .WithMany("AiChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AiChatSessions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Entities.Department", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "DeletedByNavigation")
                        .WithMany("Departments")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__Departmen__Delet__3D5E1FD2");

                    b.Navigation("DeletedByNavigation");
                });

            modelBuilder.Entity("backend.Models.Entities.Device", b =>
                {
                    b.HasOne("backend.Models.Entities.Department", "CurrentDepartment")
                        .WithMany("Devices")
                        .HasForeignKey("CurrentDepartmentId")
                        .HasConstraintName("FK__Devices__Current__3A81B327");

                    b.HasOne("backend.Models.Entities.User", "CurrentUser")
                        .WithMany("DeviceCurrentUsers")
                        .HasForeignKey("CurrentUserId")
                        .HasConstraintName("FK__Devices__Current__3B75D760");

                    b.HasOne("backend.Models.Entities.DeviceModel", "Model")
                        .WithMany("Devices")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("FK__Devices__ModelId__38996AB5");

                    b.HasOne("backend.Models.Entities.Supplier", "Supplier")
                        .WithMany("Devices")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__Devices__Supplie__398D8EEE");

                    b.HasOne("backend.Models.Entities.User", "UpdatedByNavigation")
                        .WithMany("DeviceUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__Devices__Updated__3C69FB99");

                    b.Navigation("CurrentDepartment");

                    b.Navigation("CurrentUser");

                    b.Navigation("Model");

                    b.Navigation("Supplier");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceAssignment", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DeviceAssignments_AssignedByUser");

                    b.HasOne("backend.Models.Entities.Department", "AssignedToDepartment")
                        .WithMany("DeviceAssignments")
                        .HasForeignKey("AssignedToDepartmentId")
                        .HasConstraintName("FK__DeviceAss__Assig__44FF419A");

                    b.HasOne("backend.Models.Entities.User", "AssignedToUser")
                        .WithMany("DeviceAssignments")
                        .HasForeignKey("AssignedToUserId")
                        .HasConstraintName("FK__DeviceAss__Assig__440B1D61");

                    b.HasOne("backend.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DeviceAssignments_CreatedBy");

                    b.HasOne("backend.Models.Entities.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK_DeviceAssignments_DeletedBy");

                    b.HasOne("backend.Models.Entities.Device", "Device")
                        .WithMany("DeviceAssignments")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK__DeviceAss__Devic__4316F928");

                    b.HasOne("backend.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_DeviceAssignments_UpdatedBy");

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToDepartment");

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("Device");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceHistory", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "ActionByNavigation")
                        .WithMany("DeviceHistories")
                        .HasForeignKey("ActionBy")
                        .HasConstraintName("FK__DeviceHis__Actio__5EBF139D");

                    b.HasOne("backend.Models.Entities.Device", "Device")
                        .WithMany("DeviceHistories")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK__DeviceHis__Devic__5DCAEF64");

                    b.Navigation("ActionByNavigation");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceModel", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "DeletedByNavigation")
                        .WithMany("DeviceModelDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__DeviceMod__Delet__403A8C7D");

                    b.HasOne("backend.Models.Entities.DeviceType", "DeviceType")
                        .WithMany("DeviceModels")
                        .HasForeignKey("DeviceTypeId")
                        .HasConstraintName("FK__DeviceMod__Devic__31EC6D26");

                    b.HasOne("backend.Models.Entities.User", "UpdatedByNavigation")
                        .WithMany("DeviceModelUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__DeviceMod__Updat__3F466844");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("DeviceType");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceQrToken", b =>
                {
                    b.HasOne("backend.Models.Entities.Device", "Device")
                        .WithMany("DeviceQrTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DeviceQrTokens_Devices");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceStatusLog", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "ChangedByNavigation")
                        .WithMany("DeviceStatusLogs")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("FK__DeviceSta__Chang__778AC167");

                    b.HasOne("backend.Models.Entities.Device", "Device")
                        .WithMany("DeviceStatusLogs")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK__DeviceSta__Devic__76969D2E");

                    b.Navigation("ChangedByNavigation");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("backend.Models.Entities.IncidentReport", b =>
                {
                    b.HasOne("backend.Models.Entities.Device", "Device")
                        .WithMany("IncidentReports")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK__IncidentR__Devic__49C3F6B7");

                    b.HasOne("backend.Models.Entities.User", "RejectedByNavigation")
                        .WithMany("IncidentReportRejectedByNavigations")
                        .HasForeignKey("RejectedBy")
                        .HasConstraintName("FK__IncidentR__Rejec__4BAC3F29");

                    b.HasOne("backend.Models.Entities.User", "ReportedByUser")
                        .WithMany("IncidentReportReportedByUsers")
                        .HasForeignKey("ReportedByUserId")
                        .HasConstraintName("FK__IncidentR__Repor__4AB81AF0");

                    b.Navigation("Device");

                    b.Navigation("RejectedByNavigation");

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("backend.Models.Entities.Liquidation", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "ApprovedByNavigation")
                        .WithMany("Liquidations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__Liquidati__Appro__59FA5E80");

                    b.HasOne("backend.Models.Entities.Device", "Device")
                        .WithMany("Liquidations")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK__Liquidati__Devic__59063A47");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("backend.Models.Entities.Notification", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__6383C8BA");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Entities.Repair", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "AssignedToTechnician")
                        .WithMany()
                        .HasForeignKey("AssignedToTechnicianId");

                    b.HasOne("backend.Models.Entities.User", "CostApprovedByNavigation")
                        .WithMany()
                        .HasForeignKey("CostApprovedBy")
                        .HasConstraintName("FK_Repairs_Users_CostApprovedBy");

                    b.HasOne("backend.Models.Entities.Device", "Device")
                        .WithMany("Repairs")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK__Repairs__DeviceI__5070F446");

                    b.HasOne("backend.Models.Entities.IncidentReport", "IncidentReport")
                        .WithMany("Repairs")
                        .HasForeignKey("IncidentReportId")
                        .HasConstraintName("FK__Repairs__Inciden__5165187F");

                    b.HasOne("backend.Models.Entities.User", "RejectedByNavigation")
                        .WithMany("Repairs")
                        .HasForeignKey("RejectedBy")
                        .HasConstraintName("FK__Repairs__Rejecte__52593CB8");

                    b.Navigation("AssignedToTechnician");

                    b.Navigation("CostApprovedByNavigation");

                    b.Navigation("Device");

                    b.Navigation("IncidentReport");

                    b.Navigation("RejectedByNavigation");
                });

            modelBuilder.Entity("backend.Models.Entities.RepairFeedback", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "CreatedByNavigation")
                        .WithMany("RepairFeedbacks")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__RepairFee__Creat__72C60C4A");

                    b.HasOne("backend.Models.Entities.Repair", "Repair")
                        .WithMany("RepairFeedbacks")
                        .HasForeignKey("RepairId")
                        .HasConstraintName("FK__RepairFee__Repai__71D1E811");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Repair");
                });

            modelBuilder.Entity("backend.Models.Entities.RepairImage", b =>
                {
                    b.HasOne("backend.Models.Entities.Repair", "Repair")
                        .WithMany("RepairImages")
                        .HasForeignKey("RepairId")
                        .HasConstraintName("FK__RepairIma__Repai__6C190EBB");

                    b.HasOne("backend.Models.Entities.User", "UploadedByNavigation")
                        .WithMany("RepairImages")
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("FK__RepairIma__Uploa__6D0D32F4");

                    b.Navigation("Repair");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("backend.Models.Entities.Replacement", b =>
                {
                    b.HasOne("backend.Models.Entities.Device", "NewDevice")
                        .WithMany("ReplacementNewDevices")
                        .HasForeignKey("NewDeviceId")
                        .HasConstraintName("FK__Replaceme__NewDe__5629CD9C");

                    b.HasOne("backend.Models.Entities.Device", "OldDevice")
                        .WithMany("ReplacementOldDevices")
                        .HasForeignKey("OldDeviceId")
                        .HasConstraintName("FK__Replaceme__OldDe__5535A963");

                    b.HasOne("backend.Models.Entities.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .HasConstraintName("FK_Replacements_Users_PerformedById");

                    b.Navigation("NewDevice");

                    b.Navigation("OldDevice");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("backend.Models.Entities.ReportExport", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "ExportedByNavigation")
                        .WithMany("ReportExports")
                        .HasForeignKey("ExportedBy")
                        .HasConstraintName("FK__ReportExp__Expor__6754599E");

                    b.Navigation("ExportedByNavigation");
                });

            modelBuilder.Entity("backend.Models.Entities.Supplier", b =>
                {
                    b.HasOne("backend.Models.Entities.User", "DeletedByNavigation")
                        .WithMany("Suppliers")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__Suppliers__Delet__3E52440B");

                    b.Navigation("DeletedByNavigation");
                });

            modelBuilder.Entity("backend.Models.Entities.User", b =>
                {
                    b.HasOne("backend.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Users__Departmen__2E1BDC42");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("backend.Models.Entities.AiChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("backend.Models.Entities.Department", b =>
                {
                    b.Navigation("DeviceAssignments");

                    b.Navigation("Devices");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Models.Entities.Device", b =>
                {
                    b.Navigation("DeviceAssignments");

                    b.Navigation("DeviceHistories");

                    b.Navigation("DeviceQrTokens");

                    b.Navigation("DeviceStatusLogs");

                    b.Navigation("IncidentReports");

                    b.Navigation("Liquidations");

                    b.Navigation("Repairs");

                    b.Navigation("ReplacementNewDevices");

                    b.Navigation("ReplacementOldDevices");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceModel", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("backend.Models.Entities.DeviceType", b =>
                {
                    b.Navigation("DeviceModels");
                });

            modelBuilder.Entity("backend.Models.Entities.IncidentReport", b =>
                {
                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("backend.Models.Entities.Repair", b =>
                {
                    b.Navigation("RepairFeedbacks");

                    b.Navigation("RepairImages");
                });

            modelBuilder.Entity("backend.Models.Entities.Supplier", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("backend.Models.Entities.User", b =>
                {
                    b.Navigation("AiChatSessions");

                    b.Navigation("Departments");

                    b.Navigation("DeviceAssignments");

                    b.Navigation("DeviceCurrentUsers");

                    b.Navigation("DeviceHistories");

                    b.Navigation("DeviceModelDeletedByNavigations");

                    b.Navigation("DeviceModelUpdatedByNavigations");

                    b.Navigation("DeviceStatusLogs");

                    b.Navigation("DeviceUpdatedByNavigations");

                    b.Navigation("IncidentReportRejectedByNavigations");

                    b.Navigation("IncidentReportReportedByUsers");

                    b.Navigation("Liquidations");

                    b.Navigation("Notifications");

                    b.Navigation("RepairFeedbacks");

                    b.Navigation("RepairImages");

                    b.Navigation("Repairs");

                    b.Navigation("ReportExports");

                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
