import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Table, TableHead, TableRow, TableCell, TableBody, IconButton, Tooltip, Chip, } from '@mui/material';
import EditIcon from '@mui/icons-material/Edit';
import DeleteIcon from '@mui/icons-material/Delete';
import RestoreIcon from '@mui/icons-material/Restore';
import { format } from 'date-fns';
import { vi } from 'date-fns/locale';
const SupplierTable = ({ data, onEdit, onDelete, onRestore, isAdmin }) => {
    return (_jsxs(Table, { children: [_jsx(TableHead, { children: _jsxs(TableRow, { children: [_jsx(TableCell, { children: "T\u00EAn nh\u00E0 cung c\u1EA5p" }), _jsx(TableCell, { children: "Tr\u1EA1ng th\u00E1i" }), _jsx(TableCell, { children: "Li\u00EAn h\u1EC7" }), _jsx(TableCell, { children: "Email" }), _jsx(TableCell, { children: "\u0110i\u1EC7n tho\u1EA1i" }), _jsx(TableCell, { children: "S\u1ED1 thi\u1EBFt b\u1ECB" }), _jsx(TableCell, { children: "C\u1EADp nh\u1EADt" }), isAdmin && _jsx(TableCell, { align: "center", children: "H\u00E0nh \u0111\u1ED9ng" })] }) }), _jsx(TableBody, { children: data.map((row) => (_jsxs(TableRow, { hover: true, children: [_jsx(TableCell, { children: row.supplierName }), _jsx(TableCell, { children: row.isDeleted ? (_jsx(Chip, { size: "small", color: "warning", label: "\u0110\u00E3 xo\u00E1" })) : (_jsx(Chip, { size: "small", color: "success", label: "\u0110ang ho\u1EA1t \u0111\u1ED9ng" })) }), _jsx(TableCell, { children: row.contactPerson || '-' }), _jsx(TableCell, { children: row.email || '-' }), _jsx(TableCell, { children: row.phone || '-' }), _jsx(TableCell, { children: row.deviceCount ?? 0 }), _jsx(TableCell, { children: row.updatedAt ? format(new Date(new Date(row.updatedAt).getTime() + 7 * 60 * 60 * 1000), 'dd/MM/yyyy HH:mm', { locale: vi }) : '—' }), isAdmin && (_jsx(TableCell, { align: "center", children: row.isDeleted ? (_jsx(Tooltip, { title: "Kh\u00F4i ph\u1EE5c", children: _jsx(IconButton, { onClick: () => onRestore(row.id), children: _jsx(RestoreIcon, {}) }) })) : (_jsxs(_Fragment, { children: [_jsx(Tooltip, { title: "Ch\u1EC9nh s\u1EEDa", children: _jsx(IconButton, { onClick: () => onEdit(row), children: _jsx(EditIcon, {}) }) }), _jsx(Tooltip, { title: "Xo\u00E1", children: _jsx(IconButton, { onClick: () => onDelete(row.id), children: _jsx(DeleteIcon, {}) }) })] })) }))] }, row.id))) })] }));
};
export default SupplierTable;
